name: nn4nlp-hw3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - flake8=3.7.9
  - future=0.18.2
  - ipython=7.13.0
  - numpy=1.18.1
  - pip=20.0.2
  - pyflakes=2.1.1
  - pynvim=0.4.1
  - python=3.6.10
  - pytorch=1.4.0
  - tqdm=4.43.0
  - yapf=0.29.0
  - typing=3.6.4
  - portalocker=1.5.2
  - tensorboard=1.15.0
  - nvidia-apex=0.1
  - regex=2020.2.20
  - six=1.14.0
  - click=7.1.1
  - joblib=0.14.1
  - torchtext=0.5.0
  - pip:
    - pytorch-lightning==0.7.1
    - subword-nmt==0.3.7
    - sacrebleu==1.4.4
    - sacremoses==0.0.38
